apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: poll-modem
  namespace: poll-modem
  annotations:
    cert-manager.io/cluster-issuer: letsencrypt-prod
spec:
  ingressClassName: traefik
  tls:
    - hosts:
        - modem.crib.scapegoat.dev
      secretName: poll-modem-tls
  rules:
    - host: modem.crib.scapegoat.dev
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: poll-modem
                port:
                  name: http
