apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: poll-modem-data
  namespace: poll-modem
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-path
  resources:
    requests:
      storage: 1Gi
