apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: poll-modem
  namespace: poll-modem
spec:
  namespaceSelector:
    matchNames:
      - poll-modem
  selector:
    matchLabels:
      app: poll-modem
  endpoints:
    - port: http
      path: /metrics
      interval: 30s
      scrapeTimeout: 10s
