apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: crib-scapegoat-dev-wildcard
  namespace: cert-manager
  annotations:
    argocd.argoproj.io/sync-wave: "0"
spec:
  secretName: crib-scapegoat-dev-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
    - '*.crib.scapegoat.dev'
