apiVersion: helm.cattle.io/v1
kind: HelmChartConfig
metadata:
  name: traefik
  namespace: kube-system
  annotations:
    argocd.argoproj.io/sync-wave: "-2"
spec:
  valuesContent: |-
    service:
      type: NodePort
    deployment:
      hostNetwork: true
    securityContext:
      capabilities:
        drop: []
        add:
          - NET_BIND_SERVICE
      runAsNonRoot: false
      runAsUser: 0
    ports:
      web:
        hostPort: 80
      websecure:
        hostPort: 443
